### ISSUE TITLE
Hash func

### ISSUE THREAD

**Issue by IanaKhitsko** [pavlovskyive/kpi-euro-diffusion#10]
https://github.com/pavlovskyive/kpi-euro-diffusion/blob/c0c65d0da254bfb6405f00ed00494863227a55d9/EuroDiffusion/Model/City.swift#L63

do we ever use it?

**Comment by pavlovskyive** [comment]
Class City needs to conform to Hashable and Equatable protocols to be used in Sets:

https://github.com/pavlovskyive/kpi-euro-diffusion/blob/c0c65d0da254bfb6405f00ed00494863227a55d9/EuroDiffusion/Model/City.swift#L31
