### ISSUE TITLE
Set of cities 

### ISSUE THREAD

**Issue by IanaKhitsko** [pavlovskyive/kpi-euro-diffusion#7]
https://github.com/pavlovskyive/kpi-euro-diffusion/blob/c0c65d0da254bfb6405f00ed00494863227a55d9/EuroDiffusion/Model/DiffusionManager.swift#L33

Do you pass here the refs to the objects or the objects copies?  (please explain for non-swift dev)

**Comment by pavlovskyive** [comment]
Classes are reference types in Swift (opposed to structs), so refs to the objects.
