### ISSUE TITLE
Magic -1

### ISSUE THREAD

**Issue by IanaKhitsko** [pavlovskyive/kpi-euro-diffusion#9]
https://github.com/pavlovskyive/kpi-euro-diffusion/blob/c0c65d0da254bfb6405f00ed00494863227a55d9/EuroDiffusion/Model/DiffusionManager.swift#L128

Can this part of code be more readable? What does "state[index].1 == -1 " mean here?

**Comment by pavlovskyive** [comment]
state is an array of tuples, where first value is a country and the second one is the day when diffusion was completed.
Value of state.1 == -1 means that it was not yet written as completed.

Readability improvement is on the way
